version: '3.8'
services:
  # Serviço para o PostgreSQL
  db:
    image: postgres:16
    container_name: url_shortener_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  # Serviço para o Redis
  redis:
    image: redis:latest
    container_name: url_shortener_redis
    ports:
      - '6379:6379'
    networks:
      - app-network

  # Serviço para a aplicação Node.js
  app:
    build: .
    container_name: url_shortener_app
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: '{DATABASE_URL}'
      REDIS_URL: 'redis://redis:6379'
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
